wsk -i action update query-for-travel --docker alansandrade/queryfortravel:latest
wsk -i action update seat-service --docker alansandrade/seatservice:latest
wsk -i action update save-order-info --docker alansandrade/saveorderinfo:latest
wsk -i action update query-for-station-id-by-station-name --docker alansandrade/queryforstationidbystationname:latest
wsk -i action update query-config-entity-by-config-name --docker alansandrade/queryconfigentitybyconfigname:latest
wsk -i action update get-plane-type-by-trip-id --docker alansandrade/getplanetypebytripid:latest
wsk -i action update get-plane-type-by-plane-type-id --docker alansandrade/getplanetypebyplanetypeid:latest
wsk -i action update get-sold-tickets --docker alansandrade/getsoldtickets:latest
wsk -i action update get-route-by-route-id --docker alansandrade/getroutebyrouteid:latest
wsk -i action update get-route-by-trip-id --docker alansandrade/getroutebytripid:latest
wsk -i action update get-price-by-route-id-and-plane-type --docker alansandrade/getpricebyrouteidandplanetype:latest
wsk -i action update get-order-by-id --docker alansandrade/getorderbyid:latest
wsk -i action update drawback --docker alansandrade/drawback:latest
wsk -i action update cancel-service --docker alansandrade/cancelservice:latest
