apiVersion: batch/v1
kind: Job
metadata:
  name: populate-redis
  namespace: openwhisk
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      initContainers:
      - name: wait-for-deploy-actions
        image: bitnami/kubectl:latest
        command:
        - sh
        - -c
        - |
          echo "Waiting for deploy-actions to complete..."
          until kubectl get job deploy-actions -n openwhisk -o jsonpath='{.status.succeeded}' | grep -q 1; do
            sleep 5
          done
      containers:
      - name: populate-redis
        image: {{ .Values.jobs.populateRedis.image }}
        imagePullPolicy: {{.Values.global.imagePullPolicy}}
        env:
        - name: REDIS_HOST
          value: {{ .Values.global.redis.host }}
        - name: REDIS_PORT
          value: "{{ .Values.global.redis.port }}"
        - name: REDIS_DB
          value: "{{ .Values.global.redis.db }}"
        command: ["sh", "-c", "
          wget -O clean.zip 'https://files.osf.io/v1/resources/6398x/providers/osfstorage/5ff8362686541a012814b8a4/?zip=' &&
          unzip clean.zip -d clean &&
          python add_distances.py &&
          python add_station.py &&
          python add_money.py &&
          python add_orders.py &&
          python add_trips.py &&
          python add_planes.py &&
          python add_priceroute.py &&
          python add_sId.py &&
          python add_sold_tickets.py &&
          python add_entities.py"]
      restartPolicy: Never
  backoffLimit: 4